# Generated by Django 4.0.2 on 2022-07-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_name', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, default='-')),
            ],
        ),
    ]
